#!/usr/bin/env bash
# triage.sh — Analyze a new GitHub issue with AI and post a plan comment.
# Called by handle_webhook.sh in background with the issue JSON as $1.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

[[ -f .env ]] && { set -a; source .env; set +a; }

source lib/github.sh
source lib/ai.sh
source lib/repo_context.sh

ISSUE_JSON="$1"
ISSUE_NUMBER=$(echo "$ISSUE_JSON" | jq -r '.number')
ISSUE_TITLE=$(echo "$ISSUE_JSON"  | jq -r '.title')
ISSUE_BODY=$(echo "$ISSUE_JSON"   | jq -r '.body // ""')

log() { echo "[triage #${ISSUE_NUMBER}] $(date -u '+%Y-%m-%dT%H:%M:%SZ') $*"; }

log "Starting — \"$ISSUE_TITLE\""

# ── Build repo context ────────────────────────────────────────────────────────
log "Building repo context"
CONTEXT=$(build_context "$ISSUE_TITLE $ISSUE_BODY")

# ── Build prompt ──────────────────────────────────────────────────────────────
PROMPT=$(cat <<PROMPT
GitHub Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}

**Issue Description:**
${ISSUE_BODY}

**Relevant Code Context:**
${CONTEXT}

Please analyze this issue thoroughly and provide a detailed response with these sections:

## Root Cause
What is likely causing this issue (be specific about files/functions if possible).

## Fix Plan
A numbered, actionable step-by-step plan. Reference exact file paths and function names where possible.

## Risk Assessment
Any edge cases, regressions, or breaking changes to watch out for.

## Estimated Effort
Low / Medium / High — brief reason.
PROMPT
)

# ── Call AI ───────────────────────────────────────────────────────────────────
log "Calling AI (provider: ${AI_PROVIDER:-anthropic})"
AI_RESPONSE=$(ai_triage "$PROMPT")

if [[ -z "$AI_RESPONSE" ]]; then
  log "ERROR: empty AI response — aborting"
  exit 1
fi

# ── Build and post plan comment ───────────────────────────────────────────────
COMMENT=$(cat <<COMMENT
## 🤖 AI Triage Plan

${AI_RESPONSE}

---
*To implement this plan automatically, comment \`/approve\` on this issue.*
*You can edit this comment to refine the plan before approving.*
*Generated by [AI Triage Bot (bash)](https://github.com)*
COMMENT
)

log "Posting plan comment"
RESULT=$(post_comment "$ISSUE_NUMBER" "$COMMENT")
COMMENT_ID=$(echo "$RESULT" | jq -r '.id // empty')

if [[ -z "$COMMENT_ID" ]]; then
  log "ERROR: failed to post comment — API response:"
  echo "$RESULT"
  exit 1
fi

log "Done — comment #${COMMENT_ID} posted"
